# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-11'

variables:
  - group: ios-pipeline
  - name: configuration
    value: 'Release'
  - name: sdk
    value: 'iphoneos'

steps:


- task: CocoaPods@0
  inputs:
    forceRepoUpdate: false

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'iOSPipeline'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/iOSPipeline.xcworkspace'
    xcodeVersion: 'default'
    signingOption: 'Do not code sign'
    
   
- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    SourceFolder: '$(system.defaultworkingdirectory)'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.artifactStagingDirectory)/output/iphoneos/Release'
    artifactName: 'drop' 
    publishLocation: 'Azure Pipelines'